# Generated by Django 4.2.2 on 2023-06-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vortex_tinker', '0003_booking_customer_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category_id',
        ),
    ]
